### ISSUE TITLE
Undefined method `prepare_for_sign' 

### ISSUE THREAD

**Issue by mthjn** [mobmewireless/origami-pdf#3]
I'm not able to reproduce https://github.com/mobmewireless/origami-pdf#prepare-a-pdf-for-signing in ruby 2.3.1p112 (2016-04-26 revision 54768) [x86_64-linux]

```
$ ruby do.rb
[info ] ...Reading header...
[info ] ...Parsing revision 1...
[info ] ...Parsing xref table...
[info ] ...Parsing trailer...
[info ] ...Propagating types...
do.rb:4:in `<main>': undefined method `prepare_for_sign' for #<Origami::PDF:0x0055f4dd4626c0> (NoMethodError)
```

**Comment by quinHD** [comment]
I had the same problem. 
You need to specify to install the gem from this repository
I solved it with this line in my Gemfile
`gem 'origami', github: "mobmewireless/origami-pdf", branch: 'master'
`
